---
apiVersion: v1
kind: Namespace
metadata:
  name: nats-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-app-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-admin-app-ns
---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
  namespace: nats-system
spec:
  size: 3
  version: "2.1.7"
  pod:
    enableConfigReload: true
  auth:
    enableServiceAccounts: true

# In cluster scope mode, the token secret will be created at the same namespace
# where the ServiceAccount is created.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
  namespace: my-admin-app-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-user
  namespace: my-app-ns

# In cluster scope mode, the NatsServiceRole definitions have to be created
# in the same namespace as the nats cluster.
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-user
  namespace: nats-system

  # Specifies which NATS cluster will be mapping this account,
  # (have to create a service role with permission per cluster).
  labels:
    nats_cluster: nats-cluster
spec:
  permissions:
    publish: ["foo.*", "foo.bar.quux"]
    subscribe: ["foo.bar", "greetings", "hello.world"]
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-admin-user
  namespace: nats-system
  labels:
    nats_cluster: nats-cluster
spec:
  permissions:
    publish: [">"]
    subscribe: [">"]

---
apiVersion: v1
kind: Pod
metadata:
  name: nats-user-pod
  namespace: my-app-ns
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - secret:
            name: "nats-user-nats-cluster-bound-token"
            items:
              - key: token
                path: "token"
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "synadia/nats-box:latest"
      tty: true
      stdin: true
      stdinOnce: true

      # Service Account Token is mounted via projected volume.
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: nats-admin-user-pod
  namespace: my-admin-app-ns
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - secret:
            name: "nats-admin-user-nats-cluster-bound-token"
            items:
              - key: token
                path: "token"
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "synadia/nats-box:latest"
      tty: true
      stdin: true
      stdinOnce: true

      # Service Account Token is mounted via projected volume.
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"
        readOnly: true
